---
name: "Base theme"
author: "Rezo Zero"
copyright: "Rezo Zero"
themeDir: "BaseTheme"
supportedLocale:
    - "en"
    - "fr"
versionRequire: "1.5.0"
importFiles:
    roles: []
    groups: []
    settings:
        - Resources/import/settings.json
    nodetypes:
        - Resources/import/node-type/ContactBlock.json
        - Resources/import/node-type/ContentBlock.json
        - Resources/import/node-type/Link.json
        - Resources/import/node-type/Neutral.json
        - Resources/import/node-type/Page.json
    tags: []
    attributes: []
    nodes:
        - Resources/import/node/node-main-menu.rzn
        - Resources/import/node/node-legals.rzn
