/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RzNav {}
}

declare global {


  interface HTMLRzNavElement extends Components.RzNav, HTMLStencilElement {}
  var HTMLRzNavElement: {
    prototype: HTMLRzNavElement;
    new (): HTMLRzNavElement;
  };
  interface HTMLElementTagNameMap {
    'rz-nav': HTMLRzNavElement;
  }
}

declare namespace LocalJSX {
  interface RzNav {}

  interface IntrinsicElements {
    'rz-nav': RzNav;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'rz-nav': LocalJSX.RzNav & JSXBase.HTMLAttributes<HTMLRzNavElement>;
    }
  }
}


